### ISSUE TITLE
Attaching Comments to the CST

### ISSUE THREAD

**Issue by bd82** [jhipster/prettier-java#117]
The comments are currently collected inside a separate array of the lexing result.
That is not sufficient for the prettier scenario as the re-printed Java Text must include all comment
in the correct places.

What we need is to attach the comments to the nearest CST node
Or perhaps even node**s** (nearest before **and** after nodes).

This was done in the previous implementation by @thorbenvh8 
by adding logic to the basic parser [lookahead flows](https://github.com/jhipster/prettier-java/blob/old-version/packages/java-parser/src/parser.js#L2809-L2881).
and also by defining [many types of Comments variants](https://github.com/jhipster/prettier-java/blob/old-version/packages/java-parser/src/tokens.js#L58-L93).

My **naive** approach would be to first try to implement this as a **post processing** phase on the parsing results rather than inside the Parser itself. The reasons behind this desired approach are:
- that the comment attaching is not mandatory for all parsing flows, so it would nice for it to be easily toggle-able.
- Post processing such as building an AST from A CST is often an order of magnitude faster than the actual parsing, so another traversale of the CST and slight modifications for it do not concern me in terms of performance.
- The parser is already quite complex, I'd rather not introduce additional complexity into it and 
   have a **strong separation of concerns** between parsing and comments attaching topics.

**Comment by bd82** [comment]
It may be worthwhile to investigate how @babel/parser attaches the comments
- https://babeljs.io/docs/en/next/babel-parser.html

**Comment by Shaolans** [comment]
Hi @bd82,
I started to look into babel-parser to try to understand how comments attachment is done.
The [first version](https://github.com/babel/babel/issues/1486) directly use the attach comments functions from estraverse but they later implemented their own based on [it](https://github.com/estools/estraverse/blob/master/estraverse.js) for performance purposes.
I am checking on estraverse the attachComments function and it seems to traverse the AST and use the offsets to attach the comments, I am not really sure of it, I am still trying to figure out how exactly it is done.

**Comment by Shaolans** [comment]
Hello,
I think I finally understood how the [function works](https://github.com/estools/estraverse/blob/master/estraverse.js) (still not quite sure if this is accurate thought). The first thing they do is to extends the range of comments (the startoffset and endoffset), it means that they "fill up" the gap of offsets of comments in between two tokens (gap made by spaces, carriage return...). I am not sure if I was clear, maybe a drawing is easier to understand.
![comments](https://github.com/Shaolans/Anything/blob/master/comments.jpg)
By doing this, they can easily find which node to attach by using a traverse tree function and compare the offsets. They are doing 2 passes, one to attach leading comments (comments that should be placed before the node ?) and one to attach trailing comments.
I think we can use the same principle as estraverse, but I think we can only attach comments to Terminal tokens since the offets are only defined here...
Maybe we should add another post processing treatment in order to add offsets on nodes ?
It could then allow us to attach comments on nodes instead of only terminals. Moreover, I have discussed with @clement26695 and it seems that he also needs offsets on nodes for the cst printer since the content of a node is not ordered (currently, when needed he has to search on children nodes to determine the order).

**Comment by bd82** [comment]
> I think we can use the same principle as estraverse,

Maybe yes, maybe no.
We may have more power than estraverse here because we can modify the behavior of the parser.

> Maybe we should add another post processing treatment in order to add offsets on nodes ?

That is possible, but may be faster to simply do it while building the cstNodes without an additional pass.
This could even be a generic feature in Chevrotain even.

>  I have discussed with @clement26695 and it seems that he also needs offsets on nodes for the cst printer since the content of a node is not ordered.

Again it is possible, but we may also gain the same result by overriding some methods in the parser
to created an ordered array of a cst node's children.
- https://github.com/SAP/chevrotain/blob/master/packages/chevrotain/src/parse/parser/traits/tree_builder.ts#L83-L103

Which approach is better? I do not know 😄 but keep a close eye on performance when investigating those.





Some thoughts on adding comments to terminals:
- https://github.com/SAP/chevrotain/issues/498#issuecomment-309689506

**Comment by Shaolans** [comment]
> We may have more power than estraverse here because we can modify the behavior of the parser.

I think so too


> Again it is possible, but we may also gain the same result by overriding some methods in the parser
> to created an ordered array of a cst node's children.
It seems to be a great idea, I am not sure if to understand, you mean instead of having a children on a  node like this:
```
{
  rulename1: [r11, r12],
  rulename2: [r21, r22],
  tokenname: [t]
  
}
```
We transformed it on something like this ```[r11, r21, r22, t, r12]``` ?
I am pretty sure I am on the wrong path but in the hypothesis that was what you meant, won't this break something on chevrotain since we change the structure of a node ?

> Some thoughts on adding comments to terminals:
> 
> SAP/chevrotain#498 (comment)
I think comments should be added on nodes and not terminals too. It makes more to me to do it that way

> Which approach is better? I do not know 😄 but keep a close eye on performance when investigating those.

What I am thinking of right now is to use estraverse principle of attaching comments but instead of traverse the cst on a post processing phase, use cstPostTerminal/addNoneTerminalToCst to attach the comments (I think by doing this it will attach comments only on the node nearest to the terminal).

**Comment by bd82** [comment]
>  you mean instead of having a children on a node like this:
We transforms it on something like this [r11, r21, r22, t, r12] ?
I am pretty sure I am on the wrong path but in the hypothesis that was what you meant, won't this break something on chevrotain since we change the structure of a node ?

Yes, but we can do **both** not just instead.
Create a childrenArr property on the CST and push everything there is the cstPostYYY methods.
Of course this creates a lot of arrays so I do not know if it would be good performance wise to do it
particularly as we do not need the order in all printing scenarios.

> What I am thinking of right now is to use estraverse principle of attaching comments but instead of traverse the cst on a post processing phase, use cstPostTerminal/addNoneTerminalToCst to attach the comments

That is an interesting idea, but how would you know which node is closest to the terminal if all nodes have not yet been created?

**Comment by Shaolans** [comment]
> Yes, but we can do both not just instead.
> Create a childrenArr property on the CST and push everything there is the cstPostYYY methods.
> Of course this creates a lot of arrays so I do not know if it would be good performance wise to do it
> particularly as we do not need the order in all printing scenarios.

I thought about it, I will give it a shot.

> That is an interesting idea, but how would you know which node is closest to the terminal if all nodes have not yet been created?

I have not tried it yet, that is some general thoughts/ideas. But I might be wrong, I just assumed that the parser traverse the tree and cstPostXXX is a method called before leaving the current node (I might be wrong, I just assumed it because it reminds me a bit of ANTLR when you build an AST, you can define functions to be called before and after entering a particular node). And since the children are built nodes we can find the comment. I thought that could work but since you are asking the question I am wondering I we can do it that way.

**Comment by bd82** [comment]
If we want to attach comments to terminals why don't we do this on the lexer result (Token Vector)?
It is **by definition** ordered by offset (increasing). So it should only be a simple linear loop to find which terminal to attach the comment to. (2 indices, one for vector array and one for comments array).

**Comment by Shaolans** [comment]
As you said [here](https://github.com/SAP/chevrotain/issues/498), I don't think we should attach comments to terminals but rather on nodes.
I tried to make a poke today [here](https://github.com/Shaolans/prettier-java/tree/attach_comments), to see if what I was thinking was possible. I tried to use the same principle of estraverse and adapted to the actual parser and it seems to work, I just attached the leadingComments to the highest node possible but as it is now, it does not attach comments that has not nodes under it. A lot of things can be optimized, since it was just a try I have not paid attention to it..
What do you think ? Should we continue this way or should I drop and find another way to attach comments ?

**Comment by bd82** [comment]
I think that when implementing the **attaching** of comments you should also implement a small scenario of **printing** of comments. That way you can best judge if you are creating a useful data structure for our prettier plugin scenario.

When parsing JSDocs for example I would like the comments on the **AST** so I know which
JSDocs belongs to which function. But when intending to re-print the original text (formatted) is this still true? our CST printer deals with Terminals directly, maybe its fine if it looks for comments on those?
I don't know... we need a prototype with an actual printer to check 😄

**Comment by Shaolans** [comment]
I tried a simple example using single-sample-runner and printing the resulting cst that I have not pushed on my branch. In our case, if we have Javadoc comments on a function, it will be attached to the classBodyDeclaration as a leadingComment so We will maybe have to check on children nodes if we want to know to which function it exactly belongs to.
I think attaching to terminals should fit our needs but I feels like we will be more limited of what we can do with comments (I may be wrong) and performance wise doing like so is much better.
What should be do about comments ?

> Yes, but we can do both not just instead.
> Create a childrenArr property on the CST and push everything there is the cstPostYYY methods.
> Of course this creates a lot of arrays so I do not know if it would be good performance wise to do it
> particularly as we do not need the order in all printing scenarios.

About the ordered arrays of nodes, I implemented it (probably not the best) and compared the parsing time (spring-boot repository (4486 files)) between the branch and the parser on the master. I have an execution time difference of about ~1000 ms. Is it okay ?
Another way, is to just put the start and end offsets on all nodes, on spring-boot repository the difference of execution is about ~300ms. So we won't have to create arrays where not needed but we will "move" the sorting process to the cst printer.

**Comment by bd82** [comment]
## Comments

How would we support comments inside statements or in multi-line statements without attach to terminals?

```javascript
var x = /* inline comment */ 666 + 777 + 888 +
           // regular comment inside multiline
          999;
```

If we do not have an answer to this question we should probably keep it at the terminal level.

## Ordered Array of nodes.
- Those milliseconds numbers are not very meaningful, regression percentage is more interesting.
- The real question for ordering is in what % of cases do we need this information?
   if we only need this info in one or two places in the printer than maybe we should not collect **all** the ordered nodes **everywhere**, if we need the ordered info for many cases and the performance cost in % is not large than we should probably implement it.

**Comment by Shaolans** [comment]
#Comments
It can be attached to the closest node of the terminal, with your example ```/* inline comment */``` will be attached to the variableInitializer node (as leadingComments) and ```// regular comment inside multiline``` can be attached as leadingComments of the unaryExpression node associated with 999.
Here is the [cst](https://pastebin.com/zsgWNwEw) resulting of parsing you example.

#Ordered Array of nodes
> Those milliseconds numbers are not very meaningful, regression percentage is more interesting.
For curiosity, how can we do it :blush: ?

> The real question for ordering is in what % of cases do we need this information?
> if we only need this info in one or two places in the printer than maybe we should not collect all the ordered nodes everywhere, if we need the ordered info for many cases and the performance cost in % is not large than we should probably implement it.
According to @clement26695, the % is low so I think the best way is to add the offsets to the nodes ? So he won't need the traverse the children nodes to sort in the cst printer. And since it is generalized, it will be easy to deal with cases we might forget.

**Comment by bd82** [comment]
## Comments
If the comments on the CSNodes work well that is fine.
Note that if you attach comments to the terminals you may be able to reach the closest CSTNodes
simply by post processing the CST and inspecting the terminal children of each CSTNode.
So these approaches may not be mutually exclusive.

> For curiosity, how can we do it 😊 ?

if it was 1000ms and now its 1200ms it takes 20% more time.

> According to @clement26695, the % is low so I think the best way is to add the offsets to the nodes ? So he won't need the traverse the children nodes to sort in the cst printer. And since it is generalized, it will be easy to deal with cases we might forget.

Sounds good.

**Comment by Shaolans** [comment]
> if it was 1000ms and now its 1200ms it takes 20% more time.

Oh it meant that :+1:, thanks !

> If the comments on the CSNodes work well that is fine.
> Note that if you attach comments to the terminals you may be able to reach the closest CSTNodes
> simply by post processing the CST and inspecting the terminal children of each CSTNode.
> So these approaches may not be mutually exclusive.

It does work somehow but not optimized at all and on a second thoughts, looks like attaching terminals is enough for our needs maybe ? But in any case, in term of performance attaching to terminals is much more faster than doing on cst nodes...
I tried attaching comments on terminals [here](https://github.com/Shaolans/prettier-java/tree/attach_comments_tokens) with this [entry](https://pastebin.com/qtcBbm9N) I have this resulting [tokens list](https://pastebin.com/AF2uwc8i).
Performance wise, I have not seen much difference comparing to the master.
Should I make a PR of this one ? Or should I need to do something else ?

**Comment by bd82** [comment]
>  Should I make a PR of this one ? Or should I need to do something else ?

I don't exactly know what you should do.
If you can attach comments to terminals and use this information to print a few comments in the printer
that is a good starting point.

We can later add the comments on the CstNodes as well.

**Comment by Shaolans** [comment]
> If you can attach comments to terminals and use this information to print a few comments in the printer
> that is a good starting point.

It looks like it does attach to the nearest terminal, we will see later when needed for the printer if this is fit for our needs

**Comment by Shaolans** [comment]
Hello @bd82, I tried to add comments print to the cst printer when comments are attached to the tokens and it seems to work but what kind of processing do we want to do on it ? Or just dump the comments at the right place.
Anyway I would like your thought about [it](https://github.com/Shaolans/prettier-java/tree/comment_print), by running prettier-java/packages/prettier-plugin-java/scripts/update-test-output.js it will parse and print the file in the folder [prettier-java/packages/prettier-plugin-java/test/hello-world/_input.java](https://github.com/Shaolans/prettier-java/blob/comment_print/packages/prettier-plugin-java/test/hello-world/_input.java) and [here](https://github.com/Shaolans/prettier-java/blob/comment_print/packages/prettier-plugin-java/test/hello-world/_output.java) is the result.

**Comment by bd82** [comment]
The output looks good.

I don't think we should do any processing on the comments.
The important thing is to not lose any comments and not change their location relative to the commented "node".

The first requirement (keep all comments) is obvious, the second one is more subtle because moving a comment could cause CI processes to break if that comment was a directive to some development tools, e.g: 
- // @ts-ignore
- // eslint directives
- // istanbual code coverage directives.

**Comment by Shaolans** [comment]
The first requirement is met since we are retrieving all the comments.
Since comments are attached to the closest token, the only way it can move is by moving the token itself and I don't think we are doing it, or at least for now ?
Should I make a PR to add comments after some "cleaning" ?

**Comment by bd82** [comment]
> Since comments are attached to the closest token, the only way it can move is by moving the token itself and I don't think we are doing it, or at least for now ?

We may do some stuff that would remove tokens, for example removing redundant parenthesis
in expressions, so have to be careful that we truly use the comments information.

> Should I make a PR to add comments after some "cleaning" ?

The output you are creating in your branch seems good, so I don't see why not...

**Comment by Shaolans** [comment]
It looks like we some cases where it does not output the comments.. For instance:
```
public class Hello {
	//hi
	
	int nothing;
}
```
will result:
```
public class Hello {
    int nothing;
}
```
The comment is attached as trailingComment to the token associated to ```{```.
But in the cst printer, we do have codes that looks like 
```
classBody(ctx) {
    const classBodyDecls = this.mapVisit(ctx.classBodyDeclaration);
    return rejectAndConcat([
      "{",
      indent(rejectAndConcat([line, rejectAndJoin(line, classBodyDecls)])),
      line,
      "}"
    ]);
  }
```
We are not using directly the toke ```{```...
I will try to have a talk with @clement26695 about that.

**Comment by bd82** [comment]
We probably need to adjust the printer to something like:

```javascriptclassBody(ctx) {
    const classBodyDecls = this.mapVisit(ctx.classBodyDeclaration);
    return rejectAndConcat([
      ctx.LCURLY[0],
      indent(rejectAndConcat([line, rejectAndJoin(line, classBodyDecls)])),
      line,
      ctx.RCURLY[0]
    ]);
  }

and modify our utilities such as `rejectAndConcat` to handle receiving IToken objects.

```

**Comment by Shaolans** [comment]
Yes, that is what I was thinking too, but there might be some cases where it is not as trivial as the one I pointed out.
