### ISSUE TITLE
Handle prettierignore

### ISSUE THREAD

**Issue by clement26695** [jhipster/prettier-java#209]
We should handle prettier ignore when specified in comments (see https://prettier.io/docs/en/ignore.html)

**Comment by Shaolans** [comment]
I do not think this is possible with the current implementation since we are attaching the comment to the token and not on the cstnode.
@bd82 Should we reconsider this implementation and attach the comments on the nodes ? It will allow us to handle prettierignore but also help a bit on the printing side but I will require a quite amount of work and our current version is working pretty well.
I also thought on another alternative, we could on the java-parser do a post processing where we traverse the cst and "tag" the node that should not be prettified since here we have access to the comments. WDYT ?

**Comment by bd82** [comment]
We now have position information on the CST nodes.
A comment Token also includes position information.
Can we link a prettier ignore comment to the **next** CSTNode via the locations?
Would that be simpler?

**Comment by Shaolans** [comment]
Yes that was the "alternative" I was suggesting by using the location information with chevrotain 4.7.0 (By the I think on your [changelog 4.7.0](http://sap.github.io/chevrotain/docs/changes/CHANGELOG.html) you linked to the wrong issue, it is the issue [932](https://github.com/SAP/chevrotain/issues/932) not [962](https://github.com/SAP/chevrotain/issues/962) for the location feature).
But if we are adding comments to the nodes for prettier ignore comment, should not we do it for all comments ? Thus changing our current implementation of comments.

**Comment by bd82** [comment]
> But if we are adding comments to the nodes for prettier ignore comment, should not we do it for all comments ? Thus changing our current implementation of comments.

In theory yes, but only if this manner of attaching comments is relevant for **regular comments**
and maybe only in the future depending on other tasks priorities.

Regular comments may have different requirements:
- Before/After tokens while Prettier comments only affect **after** node.
- Regular comments may be attached to separators (e.g commas) which are not even CSTNodes.

So I am not sure if the two scenario are truly similar enough to be implemented in the same manner.
But because you implemented the comments handling you are most qualified to decide if we can combine the implementation of the two scenarios.

**Comment by Shaolans** [comment]
Well combining the implementation should not be an issue and I agree that regular comments and prettier comments are quite different and should be handled as a special cases.
And performance wise attaching comments to tokens vs nodes the gap is not negligible.
As you are saying we can discuss on it in the future depending on the needs since both implementation has its pros/cons.

**Comment by bd82** [comment]
> As you are saying we can discuss on it in the future depending on the needs since both implementation has its pros/cons.

I am mostly saying that while it may be technical debt, it does not mean we need to resolve it **right now**.

And that the decision if its technical debt or not is in your hands as you as the deeper understanding of the problem here 😄

**Comment by bd82** [comment]
> (By the I think on your changelog 4.7.0 you linked to the wrong issue, it is the issue 932 not 962 for the location feature).

Thanks for pointing it out

**Comment by Shaolans** [comment]
> I am mostly saying that while it may be technical debt, it does not mean we need to resolve it right now.
> 
> And that the decision if its technical debt or not is in your hands as you have the deeper understanding of the problem here smile

I started to work with @clement26695 on [attaching comments](https://github.com/Shaolans/prettier-java/tree/attach_comment_node) on cst node. As we were working on it we witnessed a drop of performance about 10% to 20% compared to our current prettier.
We were discussing if the comments implementation is a technical debt and we conclude that it is not, or at least for now. We will face the same kind of problems that we currently have (on how we should display the comments depending of the situation) and won't gain much to switch on comments on cstnodes.
