### ISSUE TITLE
Enums end up on the same line squashing git diffs and changing formatting as values are added

### ISSUE THREAD

**Issue by natdempk** [jhipster/prettier-java#314]
Similar to https://github.com/jhipster/prettier-java/issues/264 and https://github.com/jhipster/prettier-java/issues/313

Enums will get collapsed onto a single line, and then later as more are added, spread back to a single line per enum. Eg. if I have 

```java
enum ChangeType { 
  MIGRATION,
  CREATED,
}
```

Initially this will get turned into:

```java
enum ChangeType { 
  MIGRATION, CREATED,
}
```

But later if I add more values over time, at some point it will get turned back into something like 
```java
enum ChangeType { 
  MIGRATION,
  CREATED,
  MORE,
  ENUM,
  VALUES,
  OVER,
  TIME,
  AS,
  THIS,
  GROWS,
}
```

This means that all the VCS history for why those enum values were added linewise is lost over time, but if we had just maintained the one-per-line formatting over time this would not be an issue, and the formatting would remain consistent as values are added. 

Are there strong arguments against having enums always be one-per-line? IMO it helps with VCS history and provides a more consistent format everywhere enums are used.

**Comment by jhaber** [comment]
This seems like a good idea to me. My general feeling is that as things grow code may get line broken where it didn't before, that's just the way it goes. However, it seems reasonable to say that enums always go on their own lines, which seems to match the typescript behavior:
https://github.com/prettier/prettier/pull/1914

**Comment by jhaber** [comment]
Wanted to clarify that I think enums are potentially worth special-casing here, but not necessarily because of the preserving line-based git history argument. I don't think that's what prettier-java should be optimizing for. It seems like a slippery slope that ends with everything pre-emptively being put on its own line. 

For example, you could certainly make a very similar argument for array literals and var-arg method calls (both of which can expand over time), which would result in code like
```java
String[] strings = { 
  "a",
};
```
Or:
```java
varArgsMethod(
  "a"
);
```

And once you've done varargs methods, you might as well treat all method calls the same way for consistency.

So I think think this is probably a good move in the enum case, if only for consistency with typescript. But in the general case I think the stance should be: if you change your code, it may get line-broken in places that it didn't before, c'est la vie
