### ISSUE TITLE
Create a standalone binary artifact

### ISSUE THREAD

**Issue by clementdessoude** [jhipster/prettier-java#326]
I would be awesome to provide a standalone artifact to run Prettier for Java in an ecosystem without node/npm

See #317

**Comment by bd82** [comment]
Perhaps with https://github.com/zeit/pkg

**Comment by Shaolans** [comment]
I tested pkg to create a binary of prettier-java and it seems to be working !
I think we can add binaries at each release, btw @clementdessoude are the release automated ?

**Comment by bd82** [comment]
You could evaluate GHR for automating binary upload to github releases.
- https://github.com/tcnksm/ghr

I use it here: https://github.com/SAP/xml-tools/blob/master/.circleci/config.yml#L65-L68

**Comment by clementdessoude** [comment]
Great news @Shaolans ! For the moment, release are not automated. Do you have a script to create the binary executable? If so, I can execute it this afternoon or tomorrow and make a release

**Comment by Shaolans** [comment]
I was just testing and I have not made a script but I done the following:
It might not be simple as running pkg on the repository since this is a prettier plugin.
- Clone https://github.com/prettier/prettier
- Checkout to the 2.0.0 (the one prettier-java use)
- npm install prettier-plugin-java (in our case we should link to the one we release)
- run pkg
It will create 3 binary by default: linux, macos and windows but this is surely customizable.

**Comment by Shaolans** [comment]
Since we have now migrated to github actions, there is an interesting action here to upload binaries on publish https://github.com/marketplace/actions/github-action-publish-binaries
