### ISSUE TITLE
Wrong indent on single method call following a constructor

### ISSUE THREAD

**Issue by stevegutz** [jhipster/prettier-java#381]
**Prettier-Java 0.7.1**

Interestingly, this works when another method is chained.

```sh
# Options (if any):
--print-width 80
```

**Input:**

```java
public class MethodWrappingFollowingContstructor {

  public static void callMethod() {
    new MethodWrappingFollowingContstructor().aLongEnoughMethodNameToForceThingsToWrap();
  }

  public void aLongEnoughMethodNameToForceThingsToWrap() {}
}
```

**Output:**

```java
public class MethodWrappingFollowingContstructor {

  public static void callMethod() {
    new MethodWrappingFollowingContstructor()
    .aLongEnoughMethodNameToForceThingsToWrap();
  }

  public void aLongEnoughMethodNameToForceThingsToWrap() {}
}
```

**Expected behavior:** The method call following the constructor should be indented 2 spaces, but is not indented at all.

Expected snippet:
```java
new MethodWrappingFollowingContstructor()
  .aLongEnoughMethodNameToForceThingsToWrap();
```

**Comment by pascalgrimaud** [comment]
I confirm the issue :)

**Comment by Shaolans** [comment]
Thanks for reporting the issue !
This is probably due to this [line](https://github.com/jhipster/prettier-java/blob/master/packages/prettier-plugin-java/src/printers/expressions.js#L318).
As we have this kind of case (currently printed):
```java
//Input
System.out.println("This operation with two very long string should break" + "in a very nice way");

//output
System.out.println(
    "This operation with two very long string should break" +
    "in a very nice way"
);
```
If we do force the indent we will get:
```java
System.out.println(
    "This operation with two very long string should break" +
    "in a very nice way"
    );
```
Which is not ideal, thus conflicting with when we chain a single method to the constructor call...
I think we probably need an ad hoc fix for this.
