### ISSUE TITLE
Parser works on browser?

### ISSUE THREAD

**Issue by saulpalv** [jhipster/prettier-java#446]
I tried running in browser as said in the readme that "it could"
![image](https://user-images.githubusercontent.com/19735362/101993170-c4787180-3c75-11eb-8e3e-9e311ff91ea0.png)

then with this simple code 
![image](https://user-images.githubusercontent.com/19735362/101993182-db1ec880-3c75-11eb-84d0-36e33ebfe7b9.png)
![image](https://user-images.githubusercontent.com/19735362/101993187-e5d95d80-3c75-11eb-870f-dc4ca9fd58f7.png)

**Comment by bd82** [comment]
That code is not so simple as it seems to bundle your code with webpack before running it 😄 .

Which version of Chevrotain is used in prettier-java?
There was a recent fix for some webpack issues:
- https://sap.github.io/chevrotain/docs/changes/CHANGELOG.html#_7-0-3-10-30-2020

Also it is possible there is something else in the prettier-java code that is written in a browser incompatible manner.

**Comment by clementdessoude** [comment]
Hi @saulpalv !

I think the issue is that the code you wrote is not a valid Java code "on its own" (it has to be wrapped in a method inside a Java class).

You can choose the parser entry point to parse any Java piece of code. In your example, the `expression` entrypoint should work (the list of accepted entrypoint can be found right [here](https://github.com/jhipster/prettier-java/blob/841036db3e1cac3872f949353a68b988ec2e64fb/packages/prettier-plugin-java/src/options.js#L9).

For your piece of code:

```
prettier.format("System.out.println(\"Hello World\")", { entrypoint: "expression" })

```

**Comment by saulpalv** [comment]
I see, thank you for the response, that java code was compiled and executed dynamically via JSHELL which accepts that input as valid and runs it.

I'll take your response 

> There is not a way (at least for the moment), to tell if there is a valid entrypoint for the given piece of code.
> I think the issue is that the code you wrote is not a valid Java code "on its own" (it has to be wrapped in a method inside a Java class).
