### ISSUE TITLE
Error formatting records

### ISSUE THREAD

**Issue by linco95** [jhipster/prettier-java#506]
I'm setting up prettier as the formatter for my project, and it has some issues to format records

**Prettier-Java 1.4.0**
**Prettier 2.2.1**

**Input:**
```java
public record PrettierTest(String test) {}
```

**Output:**
```sh
$ prettier ./src/PrettierTest.java 
src/PrettierTest.java[error] src/PrettierTest.java: Error: Sad sad panda, parsing errors detected in line: 1, column: 8!
[error] Expecting: one of these possible Token sequences:
[error]   1. ['interface']
[error]   2. ['@']
[error] but found: 'record'!
[error]         ->compilationUnit
[error]         ->ordinaryCompilationUnit
[error]         ->typeDeclaration
[error]         ->interfaceDeclaration
[error]     at Object.parse (/Users/andreas/.config/yarn/global/node_modules/java-parser/src/index.js:40:11)
[error]     at Object.parse (/Users/andreas/.config/yarn/global/node_modules/prettier-plugin-java/src/parser.js:6:26)
[error]     at Object.parse (/Users/andreas/.config/yarn/global/node_modules/prettier/index.js:13625:19)
[error]     at coreFormat (/Users/andreas/.config/yarn/global/node_modules/prettier/index.js:14899:14)
[error]     at format (/Users/andreas/.config/yarn/global/node_modules/prettier/index.js:15131:14)
[error]     at Object.formatWithCursor (/Users/andreas/.config/yarn/global/node_modules/prettier/index.js:57542:12)
[error]     at format (/Users/andreas/.config/yarn/global/node_modules/prettier/bin-prettier.js:15883:14)
[error]     at Object.formatFiles (/Users/andreas/.config/yarn/global/node_modules/prettier/bin-prettier.js:16067:16)
[error]     at Object.run (/Users/andreas/.config/yarn/global/node_modules/prettier/bin-prettier.js:16538:14)
[error]     at Object.<anonymous> (/Users/andreas/.config/yarn/global/node_modules/prettier/bin-prettier.js:16553:5)
```

Related PR #460

**Comment by linco95** [comment]
I tried running the maven plugin and that seems to be able to format these files (using java-prettier 1.3.0), suggesting that my issue might be that I might run an older version of java-prettier. 

How could I verify which version of java-prettier is being used?

**Comment by clementdessoude** [comment]
Hi @linco95 ! It seems working fine for me with version 0.14 of the [prettier-maven-plugin](https://github.com/HubSpot/prettier-maven-plugin). Maybe you can try to see what's version is used by looking into you M2 directory (`ls ~/.m2/repository/com/hubspot/maven/plugins/prettier-maven-plugin/0.14/`) 

It also seems that you can specify which version of prettier-plugin-java should be used: https://github.com/HubSpot/prettier-maven-plugin/blob/0c7687a5ed3ba905304bab6ac08a047844e4a2f8/README.md#L24

I'm closing this at this does not seems to be a prettier-java issue, but feel free to comment otherwise. Maybe @jhaber can help too, as he is the one who created the maven plugin
