### ISSUE TITLE
`prettier --write "**/*.java"` produced a new blank line after java class definition.

### ISSUE THREAD

**Issue by acbin** [jhipster/prettier-java#549]
Hi there, I have a question.

After executing command line `prettier --write "**/*.java"`, a new blank line was automatically added after java class definition. What should I do to avoid this. 

Look forward to your reply. Thanks!

![图片](https://user-images.githubusercontent.com/44314231/188442633-1d032f59-6cb8-4fdb-82ce-42461e018e9c.png)

**Comment by clementdessoude** [comment]
Hi @acbin ! Prettier is an opinionated code formatting tool, which provides on purpose only a very few options to change the formatting output. So there is no configuration to have or not have this blank line, it is a choice we made, which, in our opinion, improves most of the time the readability, and does not harm it otherwise.

To have a better understanding on why there are so few options, I recommend this page of the prettier blog: https://prettier.io/docs/en/option-philosophy.html
